version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root

hooks:
  BeforeInstall:
    - location: /scripts/befor-deploy.sh
      runas: root
  ApplicationStart:
    - location: /scripts/deploy.sh
      timeout: 358
      runas: root